# Generated by Django 4.2.15 on 2024-08-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_add_language_book_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="cover_image_url",
            new_name="cover_image",
        ),
    ]
