# Generated by Django 4.2.15 on 2024-08-29 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0001_all_models_creation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rental",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("returned", models.BooleanField(default=False)),
                ("book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rentals", to="books.book")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rentals", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalExtension",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("extension_date", models.DateTimeField(auto_now_add=True)),
                ("additional_days", models.PositiveIntegerField(default=7)),
                ("extension_count", models.PositiveIntegerField()),
                ("rental", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="extensions", to="rentals.rental")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
